version: '3'
services:
  selenium:
    image: vvoyer/selenium-standalone
    ports:
      - "4444:4444/tcp"
  app:
    build: .
    command: npm test
    depends_on:
      - selenium
    links:
      - selenium

  node:
    container_name: e2e-tests-container
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /dev/shm:/dev/shm
      - ./report:/usr/app/report
    environment:
      - HUB_HOST=selenium
      - HUB_PORT=4444
      - CIRCLECI=${CIRCLECI}
      - CIRCLE_BRANCH=${CIRCLE_BRANCH}
      - CIRCLE_SHA1=${CIRCLE_SHA1}
      - CIRCLE_BUILD_NUM=${CIRCLE_BUILD_NUM}
      - CIRCLE_BUILD_URL=${CIRCLE_BUILD_URL}
      - GITHUB_ACTIONS=${GITHUB_ACTIONS}
      - GITHUB_REF=${GITHUB_REF}
      - GITHUB_SHA=${GITHUB_SHA}
      - GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER}
      - TRAVIS=${TRAVIS}
      - TRAVIS_BRANCH=${TRAVIS_BRANCH}
      - TRAVIS_COMMIT=${TRAVIS_COMMIT}
      - TRAVIS_BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}
      - TRAVIS_BUILD_WEB_URL=${TRAVIS_BUILD_WEB_URL}
    depends_on:
      - selenium