version: '3'
services:
  selenium:
    image: vvoyer/selenium-standalone
    ports:
      - "4444:4444/tcp"
  app:
    build: .
    command: npm test
    depends_on:
      - selenium
    links:
      - selenium
      