name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Pull docker images
      run: docker-compose -f aaa.yml pull

    - name: Build docker images
      run: docker-compose -f aaa.yml build

    - name: Run tests
      run: docker-compose -f aaa.yml up --abort-on-container-exit --exit-code-from node

    - uses: actions/upload-artifact@v1 
      with:
        name: report
        path: report