name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:13.6
    services:
      chrome:
        image: selenium/standalone-chrome:latest
        env:
          HUB_HOST: selenium
          HUB_PORT: 4444
    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0
      - name: Install
        run: docker-compose up
      - name: Lint
        run: npm run test
