name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Pull docker images
      run: docker-compose pull

    - name: Build docker images
      run: docker-compose build

    - name: Install Dependencies tests
      run: npm install
      
    - name: Run tests
      run: npm run test
      
    - uses: actions/upload-artifact@v1 
      with:
        name: report
        path: report
